# Generated by Django 2.1.3 on 2018-11-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_nick', models.CharField(max_length=255, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reply_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='forum.Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.Topic'),
        ),
    ]
