# Generated by Django 2.1.3 on 2018-11-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20181120_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_nick',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forum.Comment'),
        ),
    ]
